"""add incident data constraints

Revision ID: 07f0d92f48e8
Revises: 63285f1c3a3a
Create Date: 2026-09-16 21:52:38.999387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07f0d92f48e8'
down_revision: Union[str, Sequence[str], None] = '63285f1c3a3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_incidents_priority', 'incidents', "priority IN ('low', 'medium', 'high', 'critical')")
    op.create_check_constraint('ck_incidents_status', 'incidents', "status IN ('open', 'in_progress', 'resolved', 'closed')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_incidents_status', 'incidents', type_='check')
    op.drop_constraint('ck_incidents_priority', 'incidents', type_='check')
    # ### end Alembic commands ###
