"""add indexes for foreign keys

Revision ID: 63285f1c3a3a
Revises: 3abd14ab79d0
Create Date: 2026-09-16 21:45:53.229763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63285f1c3a3a'
down_revision: Union[str, Sequence[str], None] = '3abd14ab79d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_incidents_scanner_id'), 'incidents', ['scanner_id'], unique=False)
    op.create_index(op.f('ix_scanners_branch_id'), 'scanners', ['branch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scanners_branch_id'), table_name='scanners')
    op.drop_index(op.f('ix_incidents_scanner_id'), table_name='incidents')
    # ### end Alembic commands ###
